feat: add fileBuilder
shuvijs/shuvi pull request #347
Opened 2022-07-13 12:57 UTC by Repraance

每次从reactive变更 或者watcher获取初始变动文件列表

比如 有A,B两个文件都watch了src/routes目录
当src/routes下有变动时，会通知file builder
file builder得知变动
则以A,B为变动源，遍历依赖树，获取将要更新的文件，将他们标记为pending。

如果是非watch场景，则直接对所有文件遍历依赖树。

然后同时向变动源列表派发更新。

更新：查看自己的上级依赖是否均resolved，如果是，则执行content 并更新内容，然后派发下一级依赖的更新。
如果上级依赖未resolved，则什么也不做。

每次build（watch过程中触发build一样）时，触发onBuild事件
创建一个defer
所有文件build完成后 resolve该defer，并触发onBuildComplete事件

2022-07-16 01:13 UTC, liximomo requested changes

2022-07-16 01:13 UTC, liximomo commented on packages/service/src/project/file-builder/index.ts
> +  onBuild: (eventHandler: EventHandler) => EventCanceler;
onBuild 容易有歧义，没看到onBuildComplete的时候，我以为onBuild就是构建完成的意思，建议改成 onBuildStart, onBuildEnd, 和 rollup 对齐

<img width="387" alt="image" src="https://user-images.githubusercontent.com/9816225/179328143-c12aaa70-cd44-4d90-b73a-5055916a3219.png">

2022-07-16 01:13 UTC, liximomo commented on packages/service/src/project/file-builder/index.ts
> +  const initFiles = (
这个可以改成异步的，fileOptions forEach 可以改为异步并发

2022-07-16 01:13 UTC, liximomo commented on packages/service/src/project/file-builder/index.ts
> +    id: uuid()
如果id只是用来做唯一标识，貌似name也是唯一的？

2022-07-16 01:13 UTC, liximomo commented on packages/service/src/project/file-builder/index.ts
> +      dependencies: [],
这里用 Set 替换掉array，后续只需要 push 不需要判断重复，语义上也更清晰

2022-07-16 01:13 UTC, liximomo commented on packages/service/src/project/file-builder/index.ts
> +      return;
为啥这个时候不触发 build 回调？总是触发貌似合理些？

2022-07-18 02:10 UTC, Repraance commented on packages/service/src/project/file-builder/index.ts
> +    id: uuid()
id只是用来索引的
为什么不用name，有两点
1. name是会变的。用户使用addRuntimeFile添加文件时，默认目录是.shuvi/app/files，但是用户defineFile时只需要写一个name。在api.addRuntimeFile中，会把每个文件的name替换成实际值。这是因为，fileBuilder的根目录只能设置一个。 projectBuilder的默认目录是.shuvi，而addRuntimeFile的默认根目录也是.shuvi/app/files。
2.虚拟文件（纯粹的watcher）没有name，自然无法通过name进行索引。讲道理，其实可以用content来定位文件，因为他不会变，而且必传。但是显然不是优雅的做法。

2022-07-18 02:12 UTC, Repraance commented on packages/service/src/project/file-builder/index.ts
> +  const initFiles = (
initFiles 只是初始化+收集依赖，不包含build文件的过程，所以是同步的，应该不用改成并发吧

2022-07-18 02:15 UTC, Repraance commented on packages/service/src/project/file-builder/index.ts
> +      return;
也就是 没有添加文件的场景，啥都没有，files是空数组
这样的话，onBuildStart和onBuildEnd还要触发么？

2022-07-18 02:17 UTC, Repraance commented on packages/service/src/project/file-builder/__tests__/file-builder-build.test.ts
> +        expect(files).toEqual([]);
不过，这个case里有判断onBuildHandler需要被执行，因此他如果没有触发，那么这个case必定fail
如果触发了，这个回调的判断也一定会执行

2022-07-18 02:25 UTC, liximomo requested changes

2022-07-18 02:25 UTC, liximomo commented on packages/service/src/project/file-builder/index.ts
> +    currentTimer = setTimeout(buildOnceHandler, 100);
100 提取成一个变量，不要magic number

2022-07-18 02:33 UTC, Repraance commented on packages/service/src/project/file-builder/index.ts
> +    currentTimer = setTimeout(buildOnceHandler, 100);
OK 先改成WATCH_AGGREGATE_TIME

2022-07-18 03:20 UTC, Repraance commented on packages/service/src/project/file-builder/__tests__/helper/index.ts
> +  execSync(`cp -R ${source} ${target}`);
fixed

2022-07-18 03:20 UTC, Repraance commented on packages/service/src/project/file-builder/index.ts
> +  onBuild: (eventHandler: EventHandler) => EventCanceler;
fixed

2022-07-18 03:20 UTC, Repraance commented on packages/service/src/project/file-builder/index.ts
> +      dependencies: [],
fixed

2022-07-18 03:32 UTC, liximomo commented on packages/service/src/project/file-builder/index.ts
> +      return;
需要的

2022-07-18 03:34 UTC, liximomo commented on packages/service/src/project/file-builder/index.ts
> +  const initFiles = (
每个fileOptions forEach 的逻辑可以变成异步并发吧，效率高点

2022-07-18 06:24 UTC, Repraance commented on packages/service/src/project/file-builder/index.ts
> +  const initFiles = (
fixed

2022-07-18 06:59 UTC, closed without merging