feat(fileBuilder): frequent update
shuvijs/shuvi pull request #373
Opened 2022-07-21 12:20 UTC by Repraance

**What kind of change does this PR introduce?**
feature

**Did you add tests(unit,e2e) for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

目前已发现的问题：不需要区分runningBuilds和awaitingBuilds

2022-07-21 14:50 UTC, liximomo requested changes

2022-07-21 14:50 UTC, liximomo commented on packages/service/src/project/file-builder/__tests__/file-builder-build.test.ts
> +import { getFileBuilder, defineFile } from '..';
不要用 '..' 这种路径

2022-07-22 12:11 UTC, Repraance commented on packages/service/src/project/file-builder/__tests__/file-builder-build.test.ts
> +import { getFileBuilder, defineFile } from '..';
不过 testcase 全都在 __tests__ 目录下，基本所有的test里都是这样引的，否则的话，就是../index了

2022-07-23 01:25 UTC, liximomo requested changes

2022-07-23 01:25 UTC, liximomo commented on packages/service/src/project/file-builder/defineFile.ts
> +    id: fileOption.name || uuid()
name不是不可靠吗，且他又是必填的，所以可以默认用name做id吗？

2022-07-23 01:25 UTC, liximomo commented on packages/utils/src/fileWatcher.ts
> +  aggregateTimeout: 100,
这里为啥改成100了

2022-07-23 01:25 UTC, liximomo commented on packages/service/src/project/file-builder/utils.ts
> +  const merged = new Set([...Array.from(setA), ...Array.from(setB)]);
这样确实可以判断，但是性能貌似不是很有好

2022-07-23 01:25 UTC, liximomo commented on packages/service/src/project/file-builder/__tests__/file-builder-watch.test.ts
> +    test('if current build is still running, another update should wait for it', () => {});
这个忘了？

2022-07-23 01:25 UTC, liximomo commented on packages/service/src/project/file-builder/__tests__/file-builder-watch.test.ts
> +    describe('if multiple current builds are still running, another new update comes', () => {
这个和
<img width="511" alt="image" src="https://user-images.githubusercontent.com/9816225/180585071-6a3850ca-c538-49da-bdf4-2ee3b8341a0e.png">
有什么区别？是不是重复了？这两个测试貌似是包含关系

2022-07-25 01:02 UTC, Repraance commented on packages/service/src/project/file-builder/__tests__/file-builder-watch.test.ts
> +    describe('if multiple current builds are still running, another new update comes', () => {
从逻辑上可以理解成包含，不过我在写case时想的是“简单到复杂”或者“特殊到普遍”的情况

2022-07-25 01:02 UTC, Repraance commented on packages/service/src/project/file-builder/__tests__/file-builder-watch.test.ts
> +    test('if current build is still running, another update should wait for it', () => {});
这个的确忘了 因为新增的所有 watch with dependencies and frequent updates 都是基于这个 case 扩展而来。。

2022-07-25 01:03 UTC, Repraance commented on packages/service/src/project/file-builder/defineFile.ts
> +    id: fileOption.name || uuid()
额 这个是为了方便测试加的，应该去掉

2022-07-25 02:41 UTC, Repraance commented on packages/service/src/project/file-builder/utils.ts
> +  const merged = new Set([...Array.from(setA), ...Array.from(setB)]);
fixed

2022-07-25 02:41 UTC, Repraance commented on packages/service/src/project/file-builder/__tests__/file-builder-watch.test.ts
> +    test('if current build is still running, another update should wait for it', () => {});
已移除该case

2022-07-25 02:44 UTC, Repraance commented on packages/utils/src/fileWatcher.ts
> +  aggregateTimeout: 100,
改回来了

2022-07-25 02:44 UTC, Repraance commented on packages/service/src/project/file-builder/defineFile.ts
> +    id: fileOption.name || uuid()
fixed

2022-07-26 02:27 UTC, merged