refactor: move CustomAppContext and CustomServerPluginHooks from shuv…
shuvijs/shuvi pull request #378
Opened 2022-07-26 10:17 UTC by andy-yuanchang

…i/runtime to shuvi/service

**What kind of change does this PR introduce?**
refactoring

**Did you add tests(unit,e2e) for your changes?**
No

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
No

2022-07-27 19:28 UTC, andy-yuanchang commented on packages/platform-web/shuvi-type-extensions-runtime.d.ts
> +/// <reference types="@shuvi/platform-web/shuvi-type-extensions-node" />
Make server.ts intellisense work

2022-07-28 01:01 UTC, liximomo requested changes

2022-07-28 01:01 UTC, liximomo commented on packages/service/src/core/apiTypes.ts
> +export interface CustomServerPluginHooks
这个声明应该直接放到  service/src/server/pluginTypes.ts 中

2022-07-28 01:04 UTC, liximomo requested changes

2022-07-28 01:04 UTC, liximomo commented on packages/platform-web/src/node/features/html-render/shuvi-app.ts
> +import '@shuvi/runtime';
这行感觉是多余的？ 你试试改成 export {}

2022-07-28 03:05 UTC, liximomo requested changes
/lgtm

2022-07-28 03:05 UTC, liximomo approved these changes

2022-07-28 03:06 UTC, merged