feat: remove inactive pages from hmr
shuvijs/shuvi pull request #382
Opened 2022-07-28 06:39 UTC by harrytothemoon

**What kind of change does this PR introduce?**

Remove inactive page from HMR

**Did you add tests(unit,e2e) for your changes?**

no

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

no

2022-07-28 14:02 UTC, liximomo requested changes

2022-07-28 14:02 UTC, liximomo commented on packages/service/src/server/middlewares/dev/hotMiddleware.ts
> +    modulesActivity.set(page, {
这个是不是和 updateModuleActivity 重复了？

2022-07-28 14:02 UTC, liximomo commented on packages/platform-web/src/shuvi-app/entry/client/app.ts
> +app.router.afterEach(() => {
应该用 initHMR返回的devClient对象，封装性更好点，不要直接用 @shuvi/toolpack/lib/utils/hotDevClient/websocket 这个模块，

2022-07-28 14:08 UTC, liximomo requested changes

2022-07-28 14:08 UTC, liximomo commented on packages/service/src/server/middlewares/dev/hotMiddleware.ts
> +        absolutePath: route.__componentSourceWithAffix__!,
这个不太对，应该用webpack的module id，__componentSourceWithAffix__并不是webpack的module id

2022-07-29 01:36 UTC, liximomo requested changes
/lgtm

2022-07-29 01:36 UTC, liximomo commented on packages/service/src/server/middlewares/dev/hotMiddleware.ts
> +    modulesActivity.set(page, {
setInterval(() => {
   notify(router.current)
}, 5000)

user
   detail

2022-07-29 02:07 UTC, harrytothemoon commented on packages/service/src/server/middlewares/dev/hotMiddleware.ts
> +    modulesActivity.set(page, {
改動如下
https://github.com/shuvijs/shuvi/pull/382/commits/7451df7fcfe1b8e9fa6d2e641c57f8b2544b940f

2022-08-01 10:44 UTC, merged