fix(fileBuilder): fix webpack wait fileBuilder
shuvijs/shuvi pull request #412
Opened 2022-08-23 02:00 UTC by Repraance

**What kind of change does this PR introduce?**

**Did you add tests(unit,e2e) for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2022-08-23 02:21 UTC, Repraance commented on packages/service/src/project/file-builder/fileBuilder.ts
> +  findFilesByDependencies: (
这个方法的名字和提供方式有些问题

2022-08-23 03:01 UTC, liximomo commented
200ms 出错

2022-08-25 08:31 UTC, liximomo requested changes

2022-08-25 08:31 UTC, liximomo commented on packages/service/src/lib/webpack-watch-wait-for-file-builder-plugin.ts
> +        if (checkResumeIntervalTimer) {
这里是不是写成下面这样更好点？ 取消再新建timer感觉变繁琐了
```
if（checkResumeIntervalTimer） {
  return
}
```

2022-08-25 08:31 UTC, liximomo commented on packages/service/src/lib/webpack-watch-wait-for-file-builder-plugin.ts
> +          clearTimeout(fallbackTimer);
这里不能消除 fallbackTimer 吧，可能会把另一个buildEnd事件的timer取消掉？

2022-08-25 08:45 UTC, liximomo requested changes

2022-08-25 08:45 UTC, liximomo commented on packages/service/src/lib/webpack-watch-wait-for-file-builder-plugin.ts
> +const fallbackTimeout = 1000 * 30;
改成5s

2022-08-25 08:45 UTC, liximomo commented on packages/service/src/lib/webpack-watch-wait-for-file-builder-plugin.ts
> +        if (checkResumeIntervalTimer) {
只需要一个 fallbackTimer 

invalid -> pause watch  -> onBuildEnd -> onBuildEnd
                                                   (fallbackTimer)

2022-08-25 08:50 UTC, Repraance commented on packages/service/src/project/file-builder/helpers.ts
> +import { BuildInfo, FileId, FileInfo } from './types';
appendChangedFiles 这个方法有用到

其实是想把杂七杂八的方法都挪到这里来

fileBuilder这个文件太冗长了。。

2022-08-25 12:27 UTC, merged