Feat:server render error
shuvijs/shuvi pull request #413
Opened 2022-08-23 07:51 UTC by harrytothemoon

**What kind of change does this PR introduce?**

**Did you add tests(unit,e2e) for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2022-08-23 08:33 UTC, liximomo requested changes

2022-08-23 08:33 UTC, liximomo commented on packages/error-overlay/src/view/helpers/parseStack.ts
> +const regexStatic = /static\/.+/;
这里为什么改成这样？

2022-08-23 08:33 UTC, liximomo commented on packages/platform-web/src/shuvi-app/react/view/ReactView.server.tsx
> +      renderError = err;
这里是不是直接抛错比较好？renderError 感觉比较多余

2022-08-23 08:33 UTC, liximomo commented on packages/platform-web/src/shuvi-app/react/view/ReactView.client.tsx
> +      const { getServerError } = require('@shuvi/error-overlay/umd');
这里判断一下，这个应该只有dev环境才有这段逻辑，@shuvi/error-overlay/umd 不应该包含在用户的最终生产代码里

2022-08-23 08:56 UTC, harrytothemoon commented on packages/error-overlay/src/view/helpers/parseStack.ts
> +const regexStatic = /static\/.+/;
客戶端的錯誤來源如 `http://localhost:3000/static/chunks/page-71db.js:19:15`
服務器端的錯誤來源如
`/Users/harry/Documents/GitHub/shuvi/test/fixtures/apiroutes/dist/server/server.js:18295:16`

主要是為了後續判斷路徑
` const pathName: string = path.isAbsolute(id)
      ? id
      : resolveBuildFile(buildDir, id);`

2022-08-23 10:12 UTC, liximomo commented on packages/error-overlay/src/view/helpers/parseStack.ts
> +const regexStatic = /static\/.+/;
这个 regexStatic 用在那里了，你举的例子中没看到

2022-08-23 10:25 UTC, harrytothemoon commented on packages/error-overlay/src/view/helpers/parseStack.ts
> +const regexStatic = /static\/.+/;
我的想法是
如果是從regexStatic找到static字串擷取即視為相對路徑，後續會判斷為相對路徑再由resolveBuildFile加工，若本身即為絕對路徑即使用原路徑。

依照原先regexStatic的截取方法都會被視為絕對路徑，若不先用絕對路徑區分，直接使用resolveBuildFile(buildDir, id)，有些原本就為絕對路徑的會變為如 `/Users/harry/Documents/GitHub/shuvi/test/fixtures/api-routes/dist/server/Users/harry/Documents/GitHub/shuvi/test/fixtures/api-routes/dist/server/server.js`

2022-08-23 10:33 UTC, harrytothemoon commented on packages/error-overlay/src/view/helpers/parseStack.ts
> +const regexStatic = /static\/.+/;
改動前：
舉例：
Client error:
`http://localhost:3000/static/chunks/page-71db.js:19:15` -> regexStatic -> /static/chunks/page-71db.js:19:15 -> resolveBuildFile -> `/Users/harry/Documents/GitHub/shuvi/test/fixtures/apiroutes/dist/client/static/chunks/page-71db.js:19:15`
Server Error:
`/Users/harry/Documents/GitHub/shuvi/test/fixtures/apiroutes/dist/server/server.js:18295:16` -> regexStatic -> `/Users/harry/Documents/GitHub/shuvi/test/fixtures/apiroutes/dist/server/server.js:18295:16` -> resolveBuildFile -> `/Users/harry/Documents/GitHub/shuvi/test/fixtures/api-routes/dist/server/Users/harry/Documents/GitHub/shuvi/test/fixtures/api-routes/dist/server/server.js`

2022-08-23 10:35 UTC, harrytothemoon commented on packages/error-overlay/src/view/helpers/parseStack.ts
> +const regexStatic = /static\/.+/;
改動後：
舉例：
Client error:
`http://localhost:3000/static/chunks/page-71db.js:19:15` -> regexStatic -> static/chunks/page-71db.js:19:15 -> `!isAbsolute` -> resolveBuildFile -> `/Users/harry/Documents/GitHub/shuvi/test/fixtures/apiroutes/dist/client/static/chunks/page-71db.js:19:15`

Server Error:
`/Users/harry/Documents/GitHub/shuvi/test/fixtures/apiroutes/dist/server/server.js:18295:16` -> regexStatic -> `/Users/harry/Documents/GitHub/shuvi/test/fixtures/apiroutes/dist/server/server.js:18295:16` -> `isAbsolute` -> `/Users/harry/Documents/GitHub/shuvi/test/fixtures/apiroutes/dist/server/server.js:18295:16`

2022-08-23 11:16 UTC, liximomo commented on packages/platform-web/src/shuvi-app/react/view/ReactView.server.tsx
> +      renderError = err;
`file://./${url.pathname}`

2022-08-23 11:16 UTC, liximomo commented on packages/error-overlay/src/view/helpers/parseStack.ts
> +const regexStatic = /static\/.+/;
`file://.${url.pathname}`

2022-08-24 05:16 UTC, liximomo commented on packages/platform-web/src/shuvi-app/app/server.ts
> +            serializeError: serializeError(isDev, error as any)
着里的逻辑冗余了

2022-08-24 05:32 UTC, liximomo requested changes

2022-08-24 05:32 UTC, liximomo commented on packages/platform-web/src/shuvi-app/app/server.ts
> +            message: error.data,
app.setError

1. manually -> app.setError({ code, message }) -> Error page  -> UI
2. throw error ->  app.setError(serializeError(Error))

2022-08-24 05:32 UTC, liximomo commented on packages/platform-web/src/shuvi-app/helper/serializeError.ts
> +    statusCode: 500
code,
message,

name: err.name,
source: 'server',
stack: err.stack

2022-08-24 09:23 UTC, liximomo requested changes

2022-08-24 09:23 UTC, liximomo commented on packages/platform-web/src/shuvi-app/react/view/ReactView.client.tsx
> +      setAppError(appError);
这行代码多余了吧，appError本来就是从app获取的，没有必要再set给他了？

2022-08-24 09:23 UTC, liximomo commented on packages/platform-web/src/shuvi-app/helper/serializeError.ts
> +export function serializeError(dev: boolean | undefined, err: Error): IError {
重命名成 serializeServerError,  这个方法应该不能在客户端调用 ？

2022-08-24 09:23 UTC, liximomo commented on packages/platform-web/src/shuvi-app/helper/serializeError.ts
> +export function serializeError(dev: boolean | undefined, err: Error): IError {
调整一下参数顺序，error作为第一个参数，dev作为options应该放在后面

2022-08-25 02:53 UTC, merged