fix: fix preset feature
shuvijs/shuvi pull request #445
Opened 2022-10-14 02:11 UTC by Repraance

**What kind of change does this PR introduce?**

**Did you add tests(unit,e2e) for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2022-10-14 02:28 UTC, liximomo requested changes

2022-10-14 02:28 UTC, liximomo commented on packages/service/src/core/apiTypes.ts
>  export type IPluginConfig =
```
export type SimplePluginConfig = 
  | string
  | CorePluginConstructor
  | CorePluginInstance

export type ObjectPluginConfig = {
  core: PluginConfig
  server: PluginConfig
  runtime: PluginConfig
  type: PluginConfig
}

export PluginConfig = 
 | SimplePluginConfig 
 | [SimplePluginConfig, any?] 
 | ObjectPluginConfig 
 | [ObjectPluginConfig, any?]
```

2022-10-14 02:28 UTC, liximomo commented on packages/service/src/core/apiTypes.ts
>  export type IPluginConfig =
plugin的可支持格式建议做如上调整，使其具备一致性

2022-10-14 02:33 UTC, Repraance commented on packages/service/src/core/apiTypes.ts
>  export type IPluginConfig =
额 这里还有些问题

首先是命名，CorePluginConstructor 其实就是plugin的那个对象，CorePluginInstance是createPlugin生成的instance对象，他们其实也是object

然后是使用限制，CorePluginConstructor和CorePluginInstance 其实是没有option的，因为不支持传数组。。

2022-10-17 01:30 UTC, liximomo approved these changes
lgtm

2022-10-17 01:30 UTC, merged