feat: tsconfig fast refresh
shuvijs/shuvi pull request #454
Opened 2022-10-24 13:09 UTC by harrytothemoon

**What kind of change does this PR introduce?**

**Did you add tests(unit,e2e) for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2022-10-25 13:09 UTC, liximomo requested changes

2022-10-25 13:09 UTC, liximomo commented on packages/service/src/server/shuviDevServer.ts
> +                    Object.assign(plugin.paths, tsCompilerOptions.paths);
是不是可以直接写成 plugin.paths = {... tsCompilerOptions.paths}

2022-10-25 13:09 UTC, liximomo commented on packages/service/src/server/shuviDevServer.ts
> +                  const resolvedUrlIndex = config.resolve?.modules?.findIndex(
这段逻辑在干嘛，不是很理解，config.resolve?.module里为什么会有 resolvedBaseUrl

2022-10-25 13:09 UTC, liximomo commented on packages/service/src/server/shuviDevServer.ts
>              enabledTypeScript = true;
这个变量好想没有用到？

2022-10-25 13:09 UTC, liximomo commented on packages/service/src/server/shuviDevServer.ts
> +            await this.verifyTypeScript();
为什么tsconfigChange 需要重新调用 await this.verifyTypeScript();

2022-10-25 15:36 UTC, harrytothemoon commented on packages/service/src/server/shuviDevServer.ts
> +                    Object.assign(plugin.paths, tsCompilerOptions.paths);
好的

2022-10-25 15:37 UTC, harrytothemoon commented on packages/service/src/server/shuviDevServer.ts
> +                  const resolvedUrlIndex = config.resolve?.modules?.findIndex(
本來參考next.js那以為是為了支持tsconfig baseUrl用的，他們在webpack/base-config裡有將baseUrl初始化進resolve.modules裡，剛調研了一波，發現這應該是next遺留的無用歷史代碼，此功能應已經被JsConfigPathsPlugin取代
理論上更新JsConfigPathsPlugin內的resolvedBaseUrl即可, 我會再把這段邏輯幹掉

2022-10-25 15:37 UTC, harrytothemoon commented on packages/service/src/server/shuviDevServer.ts
>              enabledTypeScript = true;
160行有用來判斷是不是一開始非useTypescript，而在server啟動的狀況下去enableTypeScript

2022-10-25 15:37 UTC, harrytothemoon commented on packages/service/src/server/shuviDevServer.ts
> +            await this.verifyTypeScript();
這裡主要是因為shuvi有關typescript的變量(如tsCompilerOptions, resolvedBaseUrl等等...)都存在 setupTypescript.ts裡，必須調用verifyTypescript去更新這些值，再調用getTypeScriptInfo才能取得更新後的值

2022-10-27 01:38 UTC, liximomo requested changes

2022-10-27 01:38 UTC, liximomo commented on packages/service/src/bundler/typescript/setupTypeScript.ts
> +    await loadJsConfig(projectDir);
这里改成 tsCompilerOptions = await loadJsConfig(), 尽量吧这全局对象的修改先知道一个小范围内

2022-10-27 01:38 UTC, liximomo commented on packages/service/src/server/shuviDevServer.ts
> +        this._serverContext.mode === 'production', // should be false
我们本书就处于shuviDevServer.ts 中，这里可以直接写死fasle，没必要动态判断

2022-10-27 01:38 UTC, liximomo commented on test/e2e/tsconfig-path-refresh.test.ts
> +  test('should recover from module not found and automatically load updated paths correctly', async () => {
这个主要测的是什么case？看描述貌似重复了？举个例子：

下面的 should automatically load added paths correctly 这个case, 他也具备 “recover from module not found and automatically load updated paths correctly” 这个特性

2022-10-28 01:31 UTC, merged