chore: improve hmr speed
shuvijs/shuvi pull request #499
Opened 2023-02-24 05:24 UTC by wangjinyang

**What kind of change does this PR introduce?**

chore: improve hmr speed

**Did you add tests(unit,e2e) for your changes?**

no

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

no

2023-03-04 01:56 UTC, liximomo requested changes

2023-03-04 01:56 UTC, liximomo commented on packages/platform-web/src/node/features/html-render/index.ts
> +          chain
这个不需要了，我在分离loader的那个pr里用另一种方式处理过了

2023-03-04 02:21 UTC, wangjinyang commented on packages/platform-web/src/node/features/html-render/index.ts
> +          chain
删掉了

2023-03-07 12:18 UTC, liximomo requested changes

2023-03-07 12:18 UTC, liximomo commented on packages/platform-web/src/node/features/html-render/index.ts
> +                    '@shuvi/platform-web/shuvi-app/react/view/ReactView.server.bare';
为什么不直接替换成 ./ReactView.server.bare

2023-03-07 14:03 UTC, merged