feat: support shuvi lint
shuvijs/shuvi pull request #519
Opened 2023-04-18 14:01 UTC by wangjinyang

**What kind of change does this PR introduce?**
feat: support shuvi lint

**Did you add tests(unit,e2e) for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
support shuvi lint

2023-04-19 01:49 UTC, liximomo requested changes

2023-04-19 01:49 UTC, liximomo commented on packages/eslint-config-shuvi/package.json
> +    "@babel/eslint-parser": "7.18.2",
依赖里好像少了 eslint-plugin-shuvi?

2023-04-19 01:49 UTC, liximomo commented on packages/eslint-config-shuvi/index.js
> +  rules: {
rule部分和next不太一致，需要讨论一下

2023-04-19 02:06 UTC, wangjinyang commented on packages/eslint-config-shuvi/package.json
> +    "@babel/eslint-parser": "7.18.2",
在下面 "@shuvi/eslint-plugin-shuvi": "1.0.22",

2023-04-19 02:09 UTC, evenchange4 requested changes

2023-04-19 02:09 UTC, evenchange4 commented on packages/shuvi/package.json
> +    "@babel/code-frame": "7.12.11",
- [ ] `"@babel/code-frame"` should be listed as a devDependencies.

2023-04-19 02:52 UTC, wangjinyang commented on packages/eslint-config-shuvi/index.js
> +  rules: {
一期只要機制，二期再 review 其餘 rules

2023-04-19 02:54 UTC, wangjinyang commented on packages/shuvi/package.json
> +    "@babel/code-frame": "7.12.11",
这个不是devDependencies是dependencies

2023-04-20 02:41 UTC, liximomo approved these changes
/lgtm

2023-04-20 02:43 UTC, merged