feat: fix hookGroup options
shuvijs/shuvi pull request #521
Opened 2023-04-26 10:34 UTC by Repraance

**What kind of change does this PR introduce?**

**Did you add tests(unit,e2e) for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2023-04-26 11:05 UTC, Repraance commented on packages/hook/src/hookGroup.ts
> +  before: [],
这次把types都移出去了。
这个文件的更改只有这里。

2023-04-27 00:15 UTC, liximomo requested changes

2023-04-27 00:15 UTC, liximomo commented on test/e2e/webpack-watch-wait-file-builder.test.ts
> +        ctx = await devFixture('webpack-watch-wait-file-builder');
为什么要删除plugins？这次的改动和这个test有什么关系

2023-04-27 01:58 UTC, Repraance commented on test/e2e/webpack-watch-wait-file-builder.test.ts
> +        ctx = await devFixture('webpack-watch-wait-file-builder');
因为这个fixture里的shuvi.config.js其实已经配置了相同的plugin。这里再配置一次就重复了。
本次增加了name重复的校验，才发现这个问题。

2023-04-27 02:10 UTC, merged