chore: remove redux dep
shuvijs/shuvi pull request #537
Opened 2023-06-21 05:57 UTC by wangjinyang

**What kind of change does this PR introduce?**

**Did you add tests(unit,e2e) for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2023-06-21 08:56 UTC, liximomo requested changes

2023-06-21 08:56 UTC, liximomo commented on package.json
> +    "clean": "git clean -dfX",
这两个命令不等价吧，感觉换成git clean不是很合理

2023-06-21 09:00 UTC, wangjinyang commented on package.json
> +    "clean": "git clean -dfX",
git clean -dfX 清理的更彻底

2023-06-22 00:28 UTC, liximomo commented on package.json
> +    "clean": "git clean -dfX",
这个更彻底并不一定是我们想要的，他可能误删除了构建产物之外的东西。比如我本地的.vscode 目录

2023-06-27 05:47 UTC, closed without merging