feat: Update chunk naming rules and fix generateFilesByRoutId bug
shuvijs/shuvi pull request #559
Opened 2023-09-14 08:17 UTC by harrytothemoon

**What kind of change does this PR introduce?**

**Did you add tests(unit,e2e) for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2023-09-15 01:24 UTC, liximomo requested changes

2023-09-15 01:24 UTC, liximomo commented on packages/platform-web/src/node/features/filesystem-routes/page/routes.ts
> +  /* webpackChunkName: "${fileName}-${id}" */
这里的变动是出于什么目的？

2023-09-15 02:07 UTC, harrytothemoon commented on packages/platform-web/src/node/features/filesystem-routes/page/routes.ts
> +  /* webpackChunkName: "${fileName}-${id}" */
這裡變動主要是next在瀏覽器看加載資源時，能很清楚的分辨layout和page而不需要自己根據id去對應
![image](https://github.com/shuvijs/shuvi/assets/45198715/befda7c2-3fa4-49b0-ae85-b45004df85e6)

2023-09-18 00:42 UTC, liximomo commented on packages/platform-web/src/node/features/filesystem-routes/page/routes.ts
> +  /* webpackChunkName: "${fileName}-${id}" */
那我们是不是也应该改成page-id 和 layout-id，而不是filename-id?

2023-09-18 01:53 UTC, harrytothemoon commented on packages/platform-web/src/node/features/filesystem-routes/page/routes.ts
> +  /* webpackChunkName: "${fileName}-${id}" */
沒太明白什麼意思，我對比了下next，他產生的chunk name也是依照convention File的name來生成的
https://nextjs.org/docs/app/building-your-application/routing#file-conventions
<img width="264" alt="image" src="https://github.com/shuvijs/shuvi/assets/45198715/9a142cf6-016d-48a0-b757-e60a86086772">

這是我們的
<img width="234" alt="image" src="https://github.com/shuvijs/shuvi/assets/45198715/35f01f21-32b1-4356-a7bc-a6599ddd3bdf">

2023-09-19 00:24 UTC, liximomo commented on packages/platform-web/src/node/features/filesystem-routes/page/routes.ts
> +  /* webpackChunkName: "${fileName}-${id}" */
ok，是我理解错了

2023-09-19 00:25 UTC, merged