fix(trace): fix trace logic & add e2e test
shuvijs/shuvi pull request #562
Opened 2023-09-21 13:33 UTC by Repraance

**What kind of change does this PR introduce?**

**Did you add tests(unit,e2e) for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2023-09-21 14:28 UTC, Repraance commented on packages/platform-web/src/shuvi-app/app/client.ts
> +  let shouldHydrate = !!ssr;
当SSR 首次渲染hydrate时，client side永远都不会执行loader。
因此，此处不需要再判断 hasHydrateData

2023-09-21 14:29 UTC, Repraance commented on packages/platform-web/src/shuvi-app/app/client.ts
> -    if (hasServerError) {
hasServerError变量和这个逻辑目前没用，因此移除。

2023-09-21 14:32 UTC, Repraance commented on packages/router/src/router.ts
> +      if (!this._ready && this._current !== START) {
avoid unexpected router ready in abort

this fixes https://github.com/shuvijs/shuvi/pull/561

2023-09-21 14:33 UTC, Repraance commented on packages/service/src/server/http-server/router.ts
> +          [SERVER_REQUEST.events.SHUVI_SERVER_HANDLE_REQUEST_START.attrs.url
attrs里添加url，以便后续数据跟踪

2023-09-21 14:44 UTC, Repraance commented on packages/platform-web/src/node/features/filesystem-routes/middleware/middleware.ts
> +      // if a middleware directly ends the response, the middlewareRoutesTrace will be recorded here
这个逻辑是server success rate 非常低的原因。
即，/health-check 的请求，SHUVI_SERVER_RUN_MIDDLEWARE_ROUTES 未被打点

2023-09-22 02:23 UTC, Repraance commented on packages/platform-web/src/shuvi-app/app/client.ts
> +  let shouldHydrate = !!ssr;
此处逻辑是为了修复

“SSR模式下，如果一个页面声明了loader，则客户端SHUVI_CLIENT_RUN_LOADERS不会被打点；如果这个页面没有声明loader，客户端SHUVI_CLIENT_RUN_LOADERS反而会被打点”的奇怪问题

2023-09-22 03:46 UTC, liximomo requested changes

2023-09-22 03:46 UTC, liximomo commented on packages/platform-web/src/shuvi-app/app/client.ts
> -    if (hasServerError) {
为什么说这个没用？

2023-09-22 03:46 UTC, liximomo commented on packages/platform-web/src/shuvi-app/react/view/ReactView.client.tsx
> +            <Trace>
Trace 放到这里ErrorBoundary和Provider之间是不是更合适？现在的话还需要人为的记住AppContainer和Trace的先后关系
<img width="368" alt="ScreenShot 2023-09-22 at 11 44 29@2x" src="https://github.com/shuvijs/shuvi/assets/9816225/753fe2b8-47be-4ae7-8140-e06865b45cf1">

2023-09-22 05:02 UTC, Repraance commented on packages/platform-web/src/shuvi-app/app/client.ts
> -    if (hasServerError) {
首先，这里的原始逻辑是，SSR首次渲染，在客户端hydrate时，如果有serverError，则跳过runLoader，直接 `return next()`。然后后续发生路由导航再次触发 beforeResolve 则不再限制。

但是，我发现，SSR首次渲染，在客户端hydrate时，永远都会跳过runLoader，直接 next()。而无论有没有serverError。

因此，新的 shouldHydrate 的逻辑，其实就包含了原本 hasServerError 的逻辑。这样依赖，hasServerError 就相当于没用了。

2023-09-22 05:03 UTC, Repraance commented on packages/platform-web/src/shuvi-app/react/view/ReactView.client.tsx
> +            <Trace>
确实

2023-09-22 06:20 UTC, Repraance commented on packages/platform-web/src/shuvi-app/react/view/ReactView.client.tsx
> +            <Trace>
已修改，不过我是把Trace放到了ErrorGuard里面。
因为ErrorGuard的父级组件总是正常渲染的。

2023-09-22 08:36 UTC, merged